name: Step 1 - Mega Download Test

on:
  workflow_dispatch:

jobs:
  test-download:
    runs-on: ubuntu-latest
    steps:
      - name: Install megatools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y megatools

      - name: Download OFP file from Mega
        run: |
          megadl "https://mega.nz/file/boB2XarS#4oD_JkOI7TPVSmCaerxxxoTcbThQWHj9zEjCZIHJW88" --path firmware.ofp

      - name: Confirm file exists
        run: |
          ls -lh firmware.ofp
