name: Decrypt OFP

on:
  workflow_dispatch:

env:
  FILELINK: "https://mega.nz/file/boB2XarS#4oD_JkOI7TPVSmCaerxxxoTcbThQWHj9zEjCZIHJW88"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y megatools p7zip-full python3 python3-pip android-sdk-libsparse-utils

      - name: Download OFP from Mega
        run: |
          megadl "$FILELINK" --path firmware.ofp

      - name: Clone repo and prepare
        uses: actions/checkout@v3

      - name: Decrypt OFP
        run: |
          mkdir extracted
          python3 ofp_extractor.py firmware.ofp extracted

      - name: Compress Decrypted Zip
        run: |
          7z a decrypted.zip ./extracted/*

      - name: Upload Decrypted ZIP
        uses: actions/upload-artifact@v3
        with:
          name: decrypted
          path: decrypted.zip
